version: '3.8'

services:
  app-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/17
    networks:
      - internal

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - app-db
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/app-db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
